# This is a SecretProviderClass example using aad-pod-identity to access the key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sql-creds
  namespace: tripinsights-backend
spec:
  provider: azure
  secretObjects:
  - secretName: tripinsights-secrets
    type: Opaque
    data:
    - key: SQL-DBNAME
      objectName: SQL-DBNAME
    - key: SQL-PASSWORD
      objectName: SQL-PASSWORD  
    - key: SQL-SERVER
      objectName: SQL-SERVER
    - key: SQL-USER
      objectName: SQL-USER
  parameters:
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    usePodIdentity: "false"               # Set to true for using aad-pod-identity to access your key vault
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: bfc959d9-e417-4676-a543-b0eea934fa22 #azurekeyvaultsecretsprovider-aks-tripinsights-danshue
    #userAssignedIdentityID: "false" 
    keyvaultName: AKSOpenHackVault       # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: SQL-DBNAME
          objectType: secret             # object types: secret, key, or cert
          objectAlias: SQL_DBNAME
        - |
          objectName: SQL-PASSWORD
          objectType: secret             
          objectAlias: SQL_PASSWORD
        - |
          objectName: SQL-SERVER
          objectType: secret             
          objectAlias: SQL_SERVER
        - |
          objectName: SQL-USER
          objectType: secret
          objectAlias: SQL_USER

    tenantId: 395d5677-3342-49b7-bb2d-44785c2ca83b                # The tenant ID of the key vault